### ISSUE TITLE
Oauth prompt appears at awkward time

### ISSUE THREAD

**Issue by kalman** [beaufortfrancois/omnidrive-chrome-extension#2]
IMO the Oauth prompt shouldn't just appear out of nowhere, it was jarring. It would be better if the omnibox search completion showed an "add account" or something in it results, which when chosen does the authentication. More control.

**Comment by beaufortfrancois** [comment]
You're right! I've updated the Omnidrive Extension in the Chrome Web Store to reflect this change.

BUG=https://github.com/beaufortfrancois/omnidrive-chrome-extension/commit/296b3c99c248023afa958967b2659eac3f35d7be

![screenshot 2015-06-08 at 12 02 45 pm](https://cloud.githubusercontent.com/assets/634478/8032455/5536c548-0dd6-11e5-9421-bc8e377dac62.png)
